version: '3'

services:

  # [プロジェクトごとに設定]webアプリケーションのコンテナ
    project1:
        build: ./docker/php
        volumes:
            - ./projects/project1/:/var/www/project1
            - ./shared/.bashrc:/root/.bashrc
            # ----------------------------------------------------------
            # vendorとstorageを除かないと表示が異常に遅くなる
            # ----------------------------------------------------------
            - storage-volume2:/var/www/reservation/storage
            - vendor-volume2:/var/www/reservation/vendor
            # ----------------------------------------------------------

    project2:
        build: ./docker/php
        volumes:
            - ./projects/project2/:/var/www/project2
            - ./shared/.bashrc:/root/.bashrc
            # ----------------------------------------------------------
            # vendorとstorageを除かないと表示が異常に遅くなる
            # ----------------------------------------------------------
            - storage-volume2:/var/www/reservation/storage
            - vendor-volume2:/var/www/reservation/vendor
            # ----------------------------------------------------------

    nginx:
        image: nginx:1.21.1
        ports:
            - "8001:8001"
            - "8002:8002"
        volumes:
            # Dockerfileで処理するためコメントアウト
            # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./projects/project1:/var/www/project1
            - ./projects/project2:/var/www/project2
            # ----------------------------------------------------------
            # vendorとstorageを除かないと表示が異常に遅くなる
            # ----------------------------------------------------------
            # /var/www/storageと/var/www/vendorにデータをマウントしないための準備
            - storage-volume1:/var/www/projectx2/storage
            - vendor-volume1:/var/www/projectx2/vendor
            - storage-volume2:/var/www/reservation/storage
            - vendor-volume2:/var/www/reservation/vendor
            # ----------------------------------------------------------
        depends_on:
            - project1
            - project2

    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: projects
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=user
            - PMA_PASSWORD=password
        depends_on:
            - mysql
        ports:
            - 8080:80

# ----------------------------------------------------------
# vendorとstorageを除かないと表示が異常に遅くなる
# ----------------------------------------------------------
# /var/www/storageと/var/www/vendorにデータをマウントしない設定
# フォルダは存在するがその中にデータはない状態となる
volumes:
    storage-volume1:
    vendor-volume1:
    storage-volume2:
    vendor-volume2:
# ----------------------------------------------------------